steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/bux-challenge/what-time-is-it:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/bux-challenge/what-time-is-it:latest']

options:
  logging: CLOUD_LOGGING_ONLY
