steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/bux-challenge/what-time-is-it/what-time-is-it:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/bux-challenge/what-time-is-it/what-time-is-it:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'what-time-is-it-service',
           '--image', 'europe-west4-docker.pkg.dev/bux-challenge/what-time-is-it/what-time-is-it:latest',
           '--platform', 'managed',
           '--region', 'europe-west4',
           '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
