steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bux-challenge/what-time-is-it:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bux-challenge/what-time-is-it:latest']

options:
  logging: CLOUD_LOGGING_ONLY
